
spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialize: false
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres
    password: pwd123

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: paymentsystem
        jdbc.lob.non_contextual_creation: true